<?php

/**
 * Created by PhpStorm.
 * User: woodenwang
 * Date: 2018/8/20
 * Time: 15:30
 */
class AdminModel extends MysqlDb
{

    /**
     * 查找所有admin_login用户
     * @return array    所有admin账号密码
     */
    public function selectAllAdmin()
    {
        $sql = "SELECT * FROM admin_login";
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    /**
     * 账号是否存在
     * @param string $condition    Email账号
     * @return bool                返回true即不存在
     */
    public function selectOneAdmin($condition)
    {
        $sql = "SELECT account FROM admin_login WHERE account = '".$condition."'";
       return empty(parent::select($sql))?true:false; // TODO: Change the autogenerated stub
    }

    /**
     * 查询到账号的所有信息
     * @param string $condition 账号
     * @return array            返回信息
     */
    public function selectOneAdminInfo($condition)
    {
        $sql = "SELECT * FROM admin_login WHERE account = '".$condition."'";
        return parent::select($sql)[0];  // TODO: Change the autogenerated stub
    }



    public function selectOneInfo ($condition)
    {
        $sql = "SELECT admin_login.Id as Id,account,password,name FROM admin_login,admin_level WHERE level = admin_level.Id AND account = '".$condition."'";
        return parent::select($sql)[0]; // TODO: Change the autogenerated stub
    }

    /**
     * 添加新的admin
     * @param string $account   账号
     * @param string $pwd       md5密码
     * @return int              影响行数
     */
    public function insertNewAdmin($account, $pwd)
    {
        $sql = "INSERT INTO admin_login(account,password) VALUES('".$account."','".$pwd."')";
       return parent::add($sql); // TODO: Change the autogenerated stub
    }

    public function updateNewAdmin($account, $pwd)
    {
        $sql = "UPDATE admin_login SET password='".$pwd."' WHERE account='".$account."'";

       //var_dump($sql);
        return parent::update($sql); // TODO: Change the autogenerated stub
    }

    /**
     * 添加新的 邮箱验证
     * @param  string $account  账号
     * @param int $code     验证码
     * @param date $oldTime    时间
     * @return int
     */
    public function insertChangePwd($account, $code, $oldTime)
    {
        $sql = "INSERT INTO admin_changePwd(account,code,oldTime) VALUES('".$account."','".$code."','".$oldTime."')";
        return parent::add($sql); // TODO: Change the autogenerated stub
    }


    /**
     * 查询 邮箱验证
     * @param $account
     * @return mixed
     */
    public function selectChangePwdInfo($account)
    {
        $sql = "SELECT * FROM admin_changePwd WHERE account = '".$account."'";
        return parent::select($sql)[0];  // TODO: Change the autogenerated stub
    }

    /**
     *
     * @param $account
     * @return int
     */
    public function deleteChangePwdInfo($account)
    {
        $sql = "DELETE FROM admin_changePwd WHERE account = '".$account."'";
        return parent::delete($sql); // TODO: Change the autogenerated stub
    }

    public function selectAdminName($account)
    {
        $sql = "SELECT name FROM admin_level WHERE id = (SELECT level FROM admin_login WHERE admin_login.account='".$account."')";
        return parent::select($sql)[0]['name']; // TODO: Change the autogenerated stub
    }



}
