<?php

/**
 * Created by PhpStorm.
 * User: woodenwang
 * Date: 2019/10/16
 * Time: 20:55
 */
class AlertModel extends MysqlDb
{
    public function selectAll()
    {
        $sql = 'SELECT alert.Id,algorithm_name,alert_content,is_alert,is_broadcast From algorithm,alert WHERE alert.algorithm_id=algorithm.Id';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }
    public function selectAll_url()
    {
        $sql = 'SELECT alert.Id,algorithm_url,alert_content,is_alert,is_broadcast,music From algorithm,alert WHERE alert.algorithm_id=algorithm.Id';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    public function insert($postArr)
    {
        $sql = "INSERT into alert(is_broadcast,is_alert,algorithm_id,alert_content) VALUES ('".$postArr["is_broadcast"]."','".$postArr["is_alert"]."','".$postArr["algorithm_id"]."','".$postArr["alert_content"]."');";
        return parent::add($sql); // TODO: Change the autogenerated stub
    }

    public function update($postArr)
    {
        $sql = "UPDATE alert SET is_broadcast='".$postArr["is_broadcast"]."',is_alert='".$postArr["is_alert"]."',algorithm_id='".$postArr["algorithm_id"]."',alert_content='".$postArr["alert_content"]."' WHERE Id=".$postArr["Id"];
        return parent::update($sql); // TODO: Change the autogenerated stub
    }
    public function delete($_id)
    {
        $sql = "DELETE FROM alert WHERE Id=".$_id;
        return parent::delete($sql); // TODO: Change the autogenerated stub
    }

}