<?php
/**
 * Created by PhpStorm.
 * User: woodenwang
 * Date: 2019/10/16
 * Time: 12:17
 */
class AlgorithmModel extends MysqlDb
{

    public function selectAll()
    {
        $sql = "select * from algorithm";
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    public function selectName()
    {
        $sql = 'SELECT Id,algorithm_url,algorithm_name FROM algorithm';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    public function insert($postArr)
    {
        $sql = "INSERT into algorithm(algorithm_name,algorithm_url,algorithm_content) VALUES ('".$postArr["algorithm_name"]."','".$postArr["algorithm_url"]."','".$postArr["algorithm_content"]."');";
        return parent::add($sql); // TODO: Change the autogenerated stub
    }
    public function delete($_id)
    {
        $sql = "DELETE FROM algorithm WHERE Id=".$_id;
        return parent::delete($sql); // TODO: Change the autogenerated stub
    }
    public function update($postArr)
    {
        $sql = "UPDATE algorithm SET algorithm_name='".$postArr["algorithm_name"]."',algorithm_url='".$postArr["algorithm_url"]."',algorithm_content='".$postArr["algorithm_content"]."' WHERE id=".$postArr["Id"];
        return parent::update($sql); // TODO: Change the autogenerated stub
    }

    public function getRowCount()
    {
        $sql = "SELECT COUNT(*) from algorithm";
        return parent::getCount($sql); // TODO: Change the autogenerated stub
    }

    public function getKeyword($_name){

        print($_name);
        $sql = "SELECT algorithm_url FROM algorithm Where algorithm_name = '".$_name."'";
        return parent::select($sql)[0]['algorithm_url'];
    }



}