<?php

/**
 * Created by PhpStorm.
 * User: woodenwang
 * Date: 2019/8/29
 * Time: 16:06
 */
class LogModel extends MysqlDb
{

    public function getLogList(){

        $sql = "SELECT * FROM logList;";

        return parent::select($sql);
    }

    public function getList()
    {
        $sql = 'SELECT logList.Id as Id,nick_name,after_imgUrl,warning_imgUrl,warning_type,warning_time,results FROM logList,camera WHERE camera_ip =Ip';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    /**
     * 更新日志状态
     * @param $_id int 字段ID
     * @return int  影响行数
     */
    public function changeStatus($_id){
        $sql = 'UPDATE logList SET results=1 WHERE id='.$_id;
        return parent::update($sql);
    }
    public function update($sql)
    {
        return parent::update($sql); // TODO: Change the autogenerated stub
    }

    public function selectSomeType($_type)
    {
        $sql = "SELECT * FROM logList  WHERE warning_type ='".$_type."'";
        //var_dump($sql);
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    public function  selectMoreType($sql_slice)
    {
        $sql =" SELECT * FROM logList  WHERE $sql_slice   ";
        return parent::select($sql); // TODO: Change the autogenerated stub
    }






    public function selectNowDay( )
    {
        $sql = 'SELECT * FROM logList WHERE to_days(warning_time) = to_days(now())';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }
    public function selectNowWeek( )
    {
        $sql = 'SELECT * FROM logList WHERE DATE_FORMAT( warning_time , "%Y%m" ) = DATE_FORMAT( CURDATE( ) , "%Y%m" )';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }
    public function selectNowMonth( )
    {
        $sql = 'SELECT * FROM logList WHERE DATE_FORMAT( warning_time, "%Y%m" ) = DATE_FORMAT( CURDATE( ) , "%Y%m" )';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }


    /**
     * 查询 处理过后的图片，前端轮播使用
     * @return array
     */
    public function selectDealImg()
    {
        $sql = 'SELECT warning_imgUrl FROM logList ';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }

    /**
     * 查询 没有处理的图片，前端轮播使用
     * @return array
     */
    public function selectImg()
    {
        $sql = 'SELECT after_imgUrl FROM logList ';
        return parent::select($sql); // TODO: Change the autogenerated stub
    }


}